services:
  postgres:
    image: postgres:16
    container_name: f1-simulator-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - f1-postgres-data:/var/lib/postgresql/data

volumes:
  f1-postgres-data: